packing_problem/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from new_app.views import UserLoginView, UserLogoutView, NewUserView, StartPageView, AddElementView, \
    UpdateElementView, ElementsView, ElementView, AddObstacleView, UpdateObstacleView, ObstaclesView, ObstacleView, \
    DeleteObstacleView, AddVehicleView, UpdateVehicleView, VehiclesView, VehicleView, DeleteVehicleView, SetTransport, \
    AvailableElements
from packing_problem import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', StartPageView.as_view(), name='main'),
    url(r'^login$', UserLoginView.as_view(), name='login'),
    url(r'^logout$', UserLogoutView.as_view(), name='logout'),
    url(r'^add_user$', NewUserView.as_view(), name='new-user'),
    url(r'^add_element$', AddElementView.as_view(), name='add-element'),
    url(r'^update_element/(?P<pk>\d+)/$', UpdateElementView.as_view(), name='update-element'),
    url(r'^elements', ElementsView.as_view(), name="elements"),
    url(r'^element/(?P<element_id>(\d)+)', ElementView.as_view(), name='element'),
    url(r'^add_obstacle$', AddObstacleView.as_view(), name='add-obstacle'),
    url(r'^update_obstacle/(?P<pk>\d+)/$', UpdateObstacleView.as_view(), name='update-obstacle'),
    url(r'^obstacles', ObstaclesView.as_view(), name="obstacles"),
    url(r'^obstacle/(?P<obstacle_id>(\d)+)', ObstacleView.as_view(), name='obstacle'),
    url(r'^delete_obstacle/(?P<pk>(\d)+)$', DeleteObstacleView.as_view(), name='delete-obstacle'),
    url(r'^add_vehicle$', AddVehicleView.as_view(), name='add-vehicle'),
    url(r'^update_vehicle/(?P<pk>\d+)/$', UpdateVehicleView.as_view(), name='update-vehicle'),
    url(r'^vehicles', VehiclesView.as_view(), name="vehicles"),
    url(r'^vehicle/(?P<vehicle_id>(\d)+)', VehicleView.as_view(), name='vehicle'),
    url(r'^delete_vehicle/(?P<pk>(\d)+)$', DeleteVehicleView.as_view(), name='delete-vehicle'),
    url(r'^set_transports/$', SetTransport.as_view(), name="set-transport"),
    url(r'^available_elements/$', AvailableElements.as_view(), name='available')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

new_app/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.aggregates import Sum


class Element(models.Model):
    name = models.CharField(max_length=32)
    weight = models.FloatField()
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Obstacle(models.Model):
    name = models.CharField(max_length=32)
    elements = models.ManyToManyField(Element)
    color = models.CharField(max_length=7,
                             unique=True,
                             validators=[RegexValidator(regex=r'^#(?:[0-9a-fA-F]{3}){1,2}$',
                                                        message='Color must be in HEXADECIMAL symbol')])


class Vehicle(models.Model):
    name = models.CharField(max_length=32)
    capacity = models.FloatField()
    image = models.ImageField(blank=True, null=True)
    price = models.FloatField()

    def __str__(self):
        return self.name

    def current_weight(self):
        transport = self.transport_set.first()
        if transport:
            weight = transport.elements.aggregate(Sum('weight'))
            if weight.get('weight__sum', 0) is None:
                return 0
            else:
                return weight.get('weight__sum')
        else:
            return 0


class Transport(models.Model):
    elements = models.ManyToManyField(Element)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    weight_left = models.FloatField(null=True)

    def __str__(self):
        return "Plan na zaladunek {}".format(self.vehicle.name)

new_app/forms.py
from django import forms

from new_app.models import Obstacle


class LoginForm (forms.Form):
    username = forms.CharField(label='Username')
    password = forms.CharField(label='Password', widget=forms.PasswordInput)


class NewUserForm(forms.Form):
    login = forms.CharField(label='login')
    password = forms.CharField(label='hasło', widget=forms.PasswordInput)
    password2 = forms.CharField(label='powtórz hasło', widget=forms.PasswordInput)
    first_name = forms.CharField(label='imie')
    last_name = forms.CharField(label='nazwisko')
    email = forms.EmailField(label='email')


class ObstacleForm(forms.ModelForm):
    class Meta:
        model = Obstacle
        widgets = {'elements': forms.CheckboxSelectMultiple()}
        fields = ('name', 'elements', 'color')

new_app/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models.aggregates import Sum
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from new_app.forms import ObstacleForm
from new_app.models import Element, Obstacle, Vehicle, Transport
from .forms import LoginForm, NewUserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse


class StartPageView(View):
    def get(self, request):
        return render(request, template_name='base.html')


class UserLoginView(View):
    def get(self, request):
        form = LoginForm()
        ctx = {
            'form': form
        }
        return render(request, template_name='login_view.html', context=ctx)

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('main'))
            return HttpResponse('no nie koniecznie')
        ctx = {
            'form': form
        }
        return render(request, template_name='base.html', context=ctx)


class UserLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(reverse('main'))


class NewUserView(View):
    def get(self, request):
        form = NewUserForm()
        ctx = {
            'form': form
        }
        return render(request, template_name='login_view.html', context=ctx)

    def post(self, request):
        form = NewUserForm(request.POST)
        if form.is_valid():
            login = form.cleaned_data['login']
            if User.objects.filter(username=login).exists():
                form.add_error('login', 'Taki login jest już zajęty')
            password = form.cleaned_data['password']
            password2 = form.cleaned_data['password2']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            if password != password2:
                form.add_error('password', 'hasła nie pasują do siebie')
            if not form.errors:
                email = form.cleaned_data['email']
                User.objects.create_user(login, email, password, first_name=first_name, last_name=last_name)
                return redirect(reverse('main'))
        ctx = {
            'form': form
        }
        return render(request, template_name='login_view.html', context=ctx)


class ElementsView(View):

    def get(self, request):
        elements = Element.objects.all()  #order by?
        if self.request.GET.get('name'):
            elements = elements.filter(name__icontains=request.GET['name'])

        if self.request.GET.get('available'):
            elements = elements.filter(available__icontains=request.GET['available'])
        cnx = {
            'elements': elements
        }
        return render(request, template_name="elements_list.html", context=cnx)


class AddElementView(CreateView):
    model = Element
    fields = '__all__'
    success_url = reverse_lazy('elements')


class UpdateElementView(UpdateView):
    model = Element
    fields = '__all__'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('elements')


class ElementView(View):
    def get(self, request, element_id):
        element = get_object_or_404(Element, pk=element_id)
        cnx = {
            'element': element,
        }
        return render(request, template_name='element.html', context=cnx)


class ObstaclesView(View):

    def get(self, request):
        obstacles = Obstacle.objects.all()  #order by?
        cnx = {
            'obstacles': obstacles
        }
        return render(request, template_name="obstacles_list.html", context=cnx)


class AddObstacleView(PermissionRequiredMixin, CreateView):

    permission_required = 'my_app.add_obstacle'
    raise_exception = True

    model = Obstacle
    form_class = ObstacleForm
    success_url = reverse_lazy('obstacles')


class UpdateObstacleView(PermissionRequiredMixin, UpdateView):

    permission_required = 'my_app.change_obstacle'
    raise_exception = True

    model = Obstacle
    fields = '__all__'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('obstacles')


class ObstacleView(View):
    def get(self, request, obstacle_id):
        obstacle = get_object_or_404(Obstacle, pk=obstacle_id)
        cnx = {
            'obstacle': obstacle,
        }
        # inna metoda na wyliczenie sumy elementów w przeszkodzie
        # weights = [element.weight for element in obstacle.elements.all()]
        # total_weight = sum(weights)
        # cnx['total_weight'] = total_weight

        django_weight = obstacle.elements.all().aggregate(Sum('weight'))  # {'weight__sum': 1431.1}
        cnx['django_weight'] = django_weight['weight__sum']
        return render(request, template_name='obstacle.html', context=cnx)


class DeleteObstacleView(PermissionRequiredMixin, DeleteView):

    permission_required = 'my_app.delete_obstacle'
    raise_exception = True

    model = Obstacle
    success_url = reverse_lazy('obstacles')


class VehiclesView(View):

    def get(self, request):
        vehicles = Vehicle.objects.all()  #order by?
        cnx = {
            'vehicles': vehicles
        }
        return render(request, template_name="vehicles_list.html", context=cnx)


class AddVehicleView(PermissionRequiredMixin, CreateView):

    permission_required = 'my_app.add_vehicle'
    raise_exception = True

    model = Vehicle
    fields = '__all__'
    success_url = reverse_lazy('vehicles')


class UpdateVehicleView(PermissionRequiredMixin, UpdateView):

    permission_required = 'my_app.change_obstacle'
    raise_exception = True

    model = Vehicle
    fields = '__all__'
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('vehicles')


class VehicleView(View):
    def get(self, request, vehicle_id):
        vehicle = get_object_or_404(Vehicle, pk=vehicle_id)
        cnx = {
            'vehicle': vehicle,
        }
        return render(request, template_name='vehicle.html', context=cnx)


class DeleteVehicleView(PermissionRequiredMixin, DeleteView):

    permission_required = 'my_app.delete_obstacle'
    raise_exception = True

    model = Vehicle
    success_url = reverse_lazy('vehicles')


class SetTransport(View):
    def get(self, request):
        # czy suma samochodow < sumy elementow
            # Sortujemy elementy po rozmiarze

        for vehicle in Vehicle.objects.all():
            transport, _ = Transport.objects.get_or_create(vehicle=vehicle)
            weigth_left = vehicle.capacity - transport.vehicle.current_weight()
            transport.weight_left = weigth_left
            transport.save()

        elements = Element.objects.filter(available=True).order_by('-weight')

        for element in elements:
                new_transport = Transport.objects.filter(weight_left__gte=element.weight).order_by('-vehicle__capacity').first()

                if new_transport is None:
                    return render(request, template_name='bad_transport.html')

                current_vehicle = new_transport.vehicle
                current_transport, _ = Transport.objects.get_or_create(vehicle=current_vehicle)
                current_transport.elements.add(element)
                element.available = False
                element.save()
                weight_left = current_vehicle.capacity - current_transport.vehicle.current_weight()
                current_transport.weight_left = weight_left
                current_transport.save()

        transports = Transport.objects.all()
        cnx = {
            'transports': transports,
        }
        return render(request, template_name='transport.html', context=cnx)


class AvailableElements(View):
    def get(self, request):
        elements = Element.objects.filter(available=False)
        elements.update(available=True)
        return redirect(reverse('elements'))

new_app/templates/bad_transport.html
{% extends "base.html" %}

{% block content %}

<h2>Nie wszystkie elementy zmieściły się do pojazdów</h2>

<p><a href="{% url 'add-vehicle' %}">Dodaj pojazd!</a> albo <a href="{% url 'elements' %}">Zmniejsz załadunek</a></p>
{% endblock %}

new_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main page</title>
</head>
<body>
<h1>Han and Chewie Cargo Smuggler's</h1>
{% if request.user.is_authenticated %}
Jesteś zalogowany jako: {{ request.user.username }}
<p><a href="{% url 'logout' %}">Wyloguj się</a></p>
{% else %}
<p><a href="{% url 'login' %}">Zaloguj się</a> <a href="{% url 'new-user' %}">Rejestracja</a></p>
{% endif %}
{% block content %}
{% if request.user.is_authenticated %}
<a href="{% url 'elements' %}">elements</a> <a href="{% url 'obstacles' %}">obstacles</a> <a href="{% url 'vehicles' %}">vehicles</a>
<h3><a href="{% url 'set-transport' %}">nowy załadunek</a></h3>
{% endif %}
{% endblock %}
</body>
</html>

new_app/templates/element.html
{% extends "base.html" %}

{% block content %}
<h2>{{ element.name }}</h2>
<p>Waga: {{ element.weight }} kg</p>
<p>Dostępny: {{ element.available }}</p>
<a href="/elements">powrót do listy</a>
{% endblock %}

new_app/templates/elements_list.html
{% extends "base.html" %}

{% block content %}
<h2>Elements list:</h2>
<h3>Search for element:</h3>
    <form action="" method="GET">
        <label>
            Element name:
            <input type="text" name="name" value="{{ filters.name }}">
        </label>
        <label>
            Check available:
            <input type="text" name="available" value="{{ filters.available }}">
        </label>
        <label>
            <input type="submit" value="Search">
        </label>
    </form>
<p><a href="{% url 'add-element' %}">Dodaj element!</a></p>
<p><a href="{% url 'available' %}">zmień wszystkie elementy na dostępne</a></p>
<ol>
    {% for element in elements %}
    <li><a href='/element/{{ element.id }}'>{{ element.name }}</a>--->
    <a href="/update_element/{{ element.id}}">modyfikuj</a></li>
    {% endfor %}
</ol>
<p><a href="{% url 'main' %}">main page</a></p>
{% endblock %}

new_app/templates/login_view.html
{% extends "base.html" %}
{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Zapisz">
</form>


{% endblock %}

new_app/templates/obstacle.html
{% extends "base.html" %}

{% block content %}
<h2>Przeszkoda: {{ obstacle.name }}</h2>
<p>Color: {{ obstacle.color }}</p>
<ol>Elementy:
    {% for element in obstacle.elements.all %}
    <li>{{ element.name }}</li>
    {% endfor %}
</ol>
<p>{{ total_weight }}</p>
<p>{{ django_weight }}</p>
<a href="/obstacles">powrót do listy</a>
{% endblock %}

new_app/templates/obstacles_list.html
{% extends "base.html" %}

{% block content %}
<h2>Obstacles list:</h2>
    <ol>
        {% for obstacle in obstacles %}
        <li><a href='/obstacle/{{ obstacle.id }}'>{{ obstacle.name }}</a>
        {% if perms.new_app.change_obstacle %}--->
        <a href="/update_obstacle/{{ obstacle.id}}">modyfikuj</a><br>
        {% endif %}
        {% if perms.new_app.delete_obstacle %}
        <a href="/delete_obstacle/{{ obstacle.id }}">usuń przeszkodę</a></li>
        {% endif %}
        {% endfor %}
    </ol>
{% if perms.new_app.add_obstacle %}
<p><a href="{% url 'add-obstacle' %}">Dodaj przeszkodę!</a></p>
{% endif %}
<p><a href="{% url 'main' %}">main page</a></p>
{% endblock %}

new_app/templates/transport.html
{% extends "base.html" %}

{% block content %}
<a href="/">main page</a>
{% for transport in transports %}
<h2>Pojazd: {{ transport.vehicle.name }} Pojemność {{ transport.vehicle.capacity }} kg</h2>
<h3>Waga elementów: {{ transport.vehicle.current_weight }} kg</h3>
<h3>Elementy:</h3>
<ol>
    {% for element in transport.elements.all %}
    <li>{{ element.name }}</li>
    {% endfor %}
</ol>
{% endfor %}
{% endblock %}

new_app/templates/vehicle.html
{% extends "base.html" %}

{% block content %}
<h2>{{ vehicle.name }}</h2>
<p>pojemność w tonach: {{ vehicle.capacity }}</p>
<p>cena: {{ vehicle.price }} PLN</p>

{% if vehicle.image != None %}
<p><img src="{{ vehicle.image.url }}" height="400" width="600"></p>
{% endif %}

<a href="/vehicles">powrót do listy</a>
{% endblock %}

new_app/templates/vehicles_list.html
{% extends "base.html" %}

{% block content %}
<h2>Vehicle list:</h2>
    <ol>
        {% for vehicle in vehicles %}
        <li><a href='/vehicle/{{ vehicle.id }}'>{{ vehicle.name }}</a>
        {% if perms.new_app.change_vehicle %}--->
        <a href="/update_vehicle/{{ vehicle.id}}">modyfikuj</a><br>
        {% endif %}
        {% if perms.new_app.delete_vehicle %}
        <a href="/delete_vehicle/{{ vehicle.id }}">usuń pojazd</a></li>
        {% endif %}
        {% endfor %}
    </ol>
{% if perms.new_app.add_vehicle %}
<p><a href="{% url 'add-vehicle' %}">Dodaj pojazd!</a></p>
{% endif %}
<p><a href="{% url 'main' %}">main page</a></p>
{% endblock %}